version: '3.9'
name: hummingbot_broker

services:
  emqx4:
    image: emqx:4
    restart: unless-stopped
    environment:
      - EMQX_NAME=emqx
      - EMQX_HOST=node1.emqx.io
      - EMQX_CLUSTER__DISCOVERY_STRATEGY=static
      - EMQX_CLUSTER__STATIC__SEEDS=[emqx@node1.emqx.io]
      - EMQX_LOADED_PLUGINS="emqx_recon,emqx_retainer,emqx_management,emqx_dashboard"
    volumes:
      - emqx4-data:/opt/emqx/data
      - emqx4-log:/opt/emqx/log
      - emqx4-etc:/opt/emqx/etc
    ports:
      - "1883:1883"  # mqtt:tcp
      - "1884:8883"  # mqtt:tcp:ssl
      - "1893:8083"  # mqtt:ws
      - "1894:8084"  # mqtt:ws:ssl
      - "8000:8081"  # http:management
      - "8001:18083"  # http:dashboard
    networks:
      emqx4-bridge:
        aliases:
        - node1.emqx.io
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx_ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5

networks:
  emqx4-bridge:
    driver: bridge

volumes:
  emqx4-data: {}
  emqx4-log: {}
  emqx4-etc: {}
