version: '3.9'
name: hummingbot_broker

services:
  emqx1:
    image: emqx:5
    restart: unless-stopped
    environment:
      - EMQX_NAME=emqx
      - EMQX_HOST=node1.emqx.local
      - EMQX_CLUSTER__DISCOVERY_STRATEGY=static
      - EMQX_CLUSTER__STATIC__SEEDS=[emqx@node1.emqx.local]
      - EMQX_LOADED_PLUGINS="emqx_recon,emqx_retainer,emqx_management,emqx_dashboard"
    volumes:
      - emqx-data:/opt/emqx/data
      - emqx-log:/opt/emqx/log
      - emqx-etc:/opt/emqx/etc
    ports:
      - "1883:1883"  # mqtt:tcp
      - "1884:8883"  # mqtt:tcp:ssl
      - "1893:8083"  # mqtt:ws
      - "1894:8084"  # mqtt:ws:ssl
      - "8000:8081"  # http:management
      - "8001:18083"  # http:dashboard
    networks:
      emqx-bridge:
        aliases:
        - node1.emqx.local
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx_ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5

  # prometheus:
  #   image: prom/prometheus:v2.21.0
  #   ports:
  #     - 9090:9090
  #   volumes:
  #     - ./prometheus:/etc/prometheus
  #     - prometheus-data:/prometheus
  #   command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
  #   networks:
  #     emqx-bridge:
  #       aliases:
  #       - prometheus.emqx.local

networks:
  emqx-bridge:
    driver: bridge

volumes:
  emqx-data: {}
  emqx-log: {}
  emqx-etc: {}
  prometheus-data: {}
